# Generated by Django 4.2 on 2023-04-17 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_feeling"),
        ("core", "0002_user"),
    ]

    operations = []
