# Generated by Django 4.2 on 2023-04-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_project_remove_userinteractions_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorites",
            old_name="news_id",
            new_name="news",
        ),
        migrations.RenameField(
            model_name="favorites",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="project_id",
            new_name="project",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="user_pub_id",
            new_name="user_pub",
        ),
    ]
