# Generated by Django 4.2 on 2023-05-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_rename_news_id_favorites_news_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user_follow",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
