# Generated by Django 4.2 on 2023-05-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_news_id_favorites_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=120)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reactions', to='core.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reactions', to='core.user')),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
            },
        ),
    ]
