# Generated by Django 4.2.1 on 2023-05-05 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_category_user_follow_alter_category_description"),
        ("core", "0011_reaction"),
    ]

    operations = []
