# Generated by Django 4.2.1 on 2023-05-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_merge_20230505_1623"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveToRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="SaveToReads",
                        to="core.news",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="SaveToReads",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="news",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="user",
        ),
        migrations.AlterField(
            model_name="reaction",
            name="description",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="emoji",
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name="Save_to_read",
        ),
    ]
