# Generated by Django 4.2.2 on 2023-06-20 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('core', '0013_savetoread_remove_reaction_news_remove_reaction_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteractions',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userinteractions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprojectfollow',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userprojectfollow',
            name='user',
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='user.user'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user'),
        ),
        migrations.AlterField(
            model_name='news',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='News', to='user.project'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='News', to='user.user'),
        ),
        migrations.AlterField(
            model_name='newsfeel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_feels', to='user.user'),
        ),
        migrations.AlterField(
            model_name='savetoread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SaveToReads', to='user.user'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserInteractions',
        ),
        migrations.DeleteModel(
            name='UserProjectFollow',
        ),
    ]
