# Generated by Django 4.2.2 on 2023-06-29 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_comments_user_alter_favorites_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
    ]
