# Generated by Django 4.2.4 on 2023-08-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("core", "0018_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="imageNew",
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name="+", to="uploader.image"),
        ),
    ]
