# Generated by Django 4.2.2 on 2023-06-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteractions',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='UserInteractions', to='project.project'),
        ),
        migrations.AlterField(
            model_name='userprojectfollow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_project_follows', to='project.project'),
        ),
    ]
